Importing libraries

In [ ]:
import pandas as pd
from google.colab import files

Reading the dataset

In [ ]:
df = pd.read_csv("AB_NYC_2019.csv")
df

       Unnamed: 0        id  ... calculated_host_listings_count  availability_365
0               0      2539  ...                              6               365
1               1      2595  ...                              2               355
2               3      3831  ...                              1               194
3               4      5022  ...                              1                 0
4               5      5099  ...                              1               129
...           ...       ...  ...                            ...               ...
38816       48782  36425863  ...                              1               147
38817       48790  36427429  ...                              6               339
38818       48799  36438336  ...                              1                87
38819       48805  36442252  ...                              1                40
38820       48852  36455809  ...                              1                 1

[38821 rows x 17 columns]

Data Cleaning

In [ ]:
df = df.dropna(axis=0)
df

       Unnamed: 0        id  ... calculated_host_listings_count  availability_365
0               0      2539  ...                              6               365
1               1      2595  ...                              2               355
2               3      3831  ...                              1               194
3               4      5022  ...                              1                 0
4               5      5099  ...                              1               129
...           ...       ...  ...                            ...               ...
38816       48782  36425863  ...                              1               147
38817       48790  36427429  ...                              6               339
38818       48799  36438336  ...                              1                87
38819       48805  36442252  ...                              1                40
38820       48852  36455809  ...                              1                 1

[38821 rows x 17 columns]

In [ ]:
df.to_csv('AB_NYC_2019.csv') 
files.download('AB_NYC_2019.csv')